---
# Configuration file for Dependabot
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
# https://github.com/dependabot/dependabot-core

version: 2

updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "weekly"


